### ISSUE TITLE
name 'create_unet_model' is not defined

### ISSUE THREAD

**Issue by xingzhewujiangboboniao** [Nandayang/Deep-Constrained-Gaussian-Network#2]
I have read your paper and am very interested in your work on image segmentation. This error was encountered while trying to run the code
"name 'create_unet_model' is not defined"
Is 'create_unet_model' a custom module? I can't find it in the code.

**Comment by Nandayang** [comment]
Hi @xingzhewujiangboboniao, I've uploaded the corresponding file. 
Meanwhile, you can change the model to what you want and there is no specific requirement for the architecture.
